apiVersion: v1
kind: Secret
metadata:
  name: {{ include "axiomnizam.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "axiomnizam.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  GATEKEEPER_ENCRYPTION_KEY: {{ (.Values.gatekeeper.encryptionKey | default (randAlphaNum 32)) | quote }}
  GATEKEEPER_HMAC_KEY: {{ (.Values.gatekeeper.hmacKey | default (randAlphaNum 32)) | quote }}
  {{- if .Values.iam.sysadminPassword }}
  IAM_SYSADMIN_PASSWORD: {{ .Values.iam.sysadminPassword | quote }}
  {{- end }}
  {{- if .Values.keycloak.enabled }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.keycloak.clientSecret | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
  {{- end }}
---
{{- if .Values.iam.rsaPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "axiomnizam.fullname" . }}-rsa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "axiomnizam.labels" . | nindent 4 }}
type: Opaque
stringData:
  rsa_private_key.pem: {{ .Values.iam.rsaPrivateKey | quote }}
{{- end }}
