// Package tls provides TLS certificate loading and self-signed certificate
// generation for development environments.
package tls

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"time"
)

// Config holds the resolved TLS configuration ready for use.
type Config struct {
	// Enabled indicates whether TLS is active.
	Enabled bool

	// CertFile is the path to the certificate file (may be auto-generated).
	CertFile string

	// KeyFile is the path to the private key file (may be auto-generated).
	KeyFile string

	// AutoGenerated is true when the certs were generated automatically.
	AutoGenerated bool
}

// LoadOrCreate resolves TLS configuration. If explicit cert/key paths are provided,
// it verifies they exist and are valid. If autoGenerate is true, it creates a
// self-signed certificate in dataDir/certs/.
func LoadOrCreate(certFile, keyFile string, autoGenerate bool, dataDir string) (*Config, error) {
	// Explicit cert/key provided
	if certFile != "" && keyFile != "" {
		if _, err := os.Stat(certFile); err != nil {
			return nil, fmt.Errorf("TLS cert file not found: %s", certFile)
		}
		if _, err := os.Stat(keyFile); err != nil {
			return nil, fmt.Errorf("TLS key file not found: %s", keyFile)
		}
		// Verify the cert/key pair is valid
		if _, err := tls.LoadX509KeyPair(certFile, keyFile); err != nil {
			return nil, fmt.Errorf("invalid TLS cert/key pair: %w", err)
		}
		return &Config{
			Enabled: true,
			CertFile: certFile,
			KeyFile:  keyFile,
		}, nil
	}

	// Auto-generate self-signed cert for development
	if autoGenerate {
		certsDir := filepath.Join(dataDir, "certs")
		if err := os.MkdirAll(certsDir, 0700); err != nil {
			return nil, fmt.Errorf("failed to create certs directory: %w", err)
		}

		genCertFile := filepath.Join(certsDir, "server.crt")
		genKeyFile := filepath.Join(certsDir, "server.key")

		// Only generate if certs don't already exist
		if _, err := os.Stat(genCertFile); os.IsNotExist(err) {
			if err := generateSelfSignedCert(genCertFile, genKeyFile); err != nil {
				return nil, fmt.Errorf("failed to generate self-signed cert: %w", err)
			}
		}

		return &Config{
			Enabled:       true,
			CertFile:      genCertFile,
			KeyFile:       genKeyFile,
			AutoGenerated: true,
		}, nil
	}

	return &Config{Enabled: false}, nil
}

// generateSelfSignedCert creates a self-signed ECDSA P-256 certificate
// valid for 365 days, covering localhost and 127.0.0.1.
func generateSelfSignedCert(certFile, keyFile string) error {
	// Generate ECDSA P-256 private key
	privateKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("failed to generate private key: %w", err)
	}

	// Create certificate template
	serialNumber, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return fmt.Errorf("failed to generate serial number: %w", err)
	}

	template := x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{"AxiomNizam Dev"},
			CommonName:   "localhost",
		},
		NotBefore:             time.Now(),
		NotAfter:              time.Now().Add(365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IPAddresses:           []net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")},
		DNSNames:              []string{"localhost"},
	}

	// Self-sign the certificate
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &privateKey.PublicKey, privateKey)
	if err != nil {
		return fmt.Errorf("failed to create certificate: %w", err)
	}

	// Write certificate file
	certOut, err := os.Create(certFile)
	if err != nil {
		return fmt.Errorf("failed to create cert file: %w", err)
	}
	defer certOut.Close()

	if err := pem.Encode(certOut, &pem.Block{Type: "CERTIFICATE", Bytes: certDER}); err != nil {
		return fmt.Errorf("failed to write cert: %w", err)
	}

	// Write private key file
	keyOut, err := os.OpenFile(keyFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("failed to create key file: %w", err)
	}
	defer keyOut.Close()

	keyDER, err := x509.MarshalECPrivateKey(privateKey)
	if err != nil {
		return fmt.Errorf("failed to marshal private key: %w", err)
	}

	if err := pem.Encode(keyOut, &pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER}); err != nil {
		return fmt.Errorf("failed to write key: %w", err)
	}

	return nil
}
